import type { MintConfig } from "@/types";

const {
    COLLECTION_MINT = "",
    COLLECTION_METADATA_ACCOUNT = "",
    COLLECTION_MASTER_EDITION_ACCOUNT = "",
    SHADOW_ACCOUNT = "",
    MERKLE_TREE = "",
} = process.env;

export const config: MintConfig  = {
    metadata: {
        name: "OPOS Outliers",
        description: "Unlimited compressed NFT characters. Only possible on Solana, powered by TipLink.",
        symbol: "OPOSOUT",
        external_url: "https://opos.quest",
        properties: {
            files: [],
            category: "image",
        },  
    },

    // Hardcoded values that represent the production environment
    productionEnvironment: {
        payer: "p7X5mwA9CKX6uZz4xwwD9Jqg3hUE9PWfgV3QBQsYfoh",
        activeTree: "tJTjTKqDdin8Xsjfb4Kx2vGcg1F7m19C53AUHnDcnCT",
        trees: [
            "tL2TAswGPHjtCvxN9ez5y8TDrAU1Pxh8PEVmHC8tiyy",
            "tJTjTKqDdin8Xsjfb4Kx2vGcg1F7m19C53AUHnDcnCT",
        ],
    },
    
    // Based on local environment
    tree: {
        publicKey: MERKLE_TREE,
        maxBufferSize: 64,
        maxDepth: 17,
        canopy: 8,
    },

    collection: {
        "collectionMint": COLLECTION_MINT,
        "collectionMetadataAccount": COLLECTION_METADATA_ACCOUNT,
        "collectionMasterEditionAccount": COLLECTION_MASTER_EDITION_ACCOUNT,
        "collectionMetadataUri": "https://shdw-drive.genesysgo.net/7J165fhor8ysTfu46LiKG76gsLzG33coqZQLqhvJYESy/1691558993463.json"
    },

    storage: {
        shadowAccount: SHADOW_ACCOUNT,
    },

    defaultAttributes: {
        Background: "Abstract",
        "Skin Color": "Human 1",
        Face: "Smile",
        Head: "TipLink Helmet",  
        Torso: "TipLink Shirt",  
        Logo: "TipLink",       
        Legs: "TipLink Pants",
        Feet: "TipLink Shoes",
    },

    attributes: {
        "Background": {
            "Abstract": "https://staging.opos.quest/attributes/Backgrounds/Abstract.png",
            "TipLink": "https://staging.opos.quest/attributes/Backgrounds/TipLink.png?2",
            "DAA": "https://staging.opos.quest/attributes/Backgrounds/DAA.png?1",
            "Blue": "https://staging.opos.quest/attributes/Backgrounds/Blue.png",
            "Green": "https://staging.opos.quest/attributes/Backgrounds/Green.png",
            "Grey": "https://staging.opos.quest/attributes/Backgrounds/Grey.png",
            "Pink": "https://staging.opos.quest/attributes/Backgrounds/Pink.png",
            "Purple": "https://staging.opos.quest/attributes/Backgrounds/Purple.png",
            "Red": "https://staging.opos.quest/attributes/Backgrounds/Red.png",
            "Solana": "https://staging.opos.quest/attributes/Backgrounds/Solana.png",
            "White": "https://staging.opos.quest/attributes/Backgrounds/White.png",
            "Yellow": "https://staging.opos.quest/attributes/Backgrounds/Yellow.png",
        },
        "Skin Color": {
            "Human 1": "https://staging.opos.quest/attributes/Heads/Color/Skin1.png",
            "Human 2": "https://staging.opos.quest/attributes/Heads/Color/Skin2.png",
            "Human 3": "https://staging.opos.quest/attributes/Heads/Color/Skin3.png",
            "Human 4": "https://staging.opos.quest/attributes/Heads/Color/Skin4.png",
            "Human 5": "https://staging.opos.quest/attributes/Heads/Color/Skin5.png",
            "Alien": "https://staging.opos.quest/attributes/Heads/Color/Alien.png",
            "Zombie": "https://staging.opos.quest/attributes/Heads/Color/Zombie.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
        "Face": {
            "Smile": "https://staging.opos.quest/attributes/Heads/Faces/BasicSmile.png",
            "Cursed": "https://staging.opos.quest/attributes/Heads/Faces/Cursed.png",
            "Duck": "https://staging.opos.quest/attributes/Heads/Faces/Duck.png",
            "Red Laser Eyes": "https://staging.opos.quest/attributes/Heads/Faces/LaserEyesRed.png",
            "Scarecrow": "https://staging.opos.quest/attributes/Heads/Faces/Scarecrow.png",
            "Vampire": "https://staging.opos.quest/attributes/Heads/Faces/Vampire.png",
            "Visor": "https://staging.opos.quest/attributes/Heads/Faces/Visor.png",
            "Solana Viper": "https://staging.opos.quest/attributes/Heads/Faces/SolanaViper.png",
            "TipLink Viper": "https://staging.opos.quest/attributes/Heads/Faces/TipLinkViper.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
        "Head": {
            "Tippy": "https://staging.opos.quest/attributes/Heads/Special/TippyHead.png",
            "Dark Tippy": "https://staging.opos.quest/attributes/Heads/Special/TippyHeadDark.png",
            "DAA": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/DAA.png",
            "Samo": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Samo.png",
            "SMB": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/SMB.png",
            "Bonk": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Bonk.png",
            "Pony Tail 1": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Pony Tail1.png",
            "Pony Tail 2": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Pony Tail2.png",
            "Pony Tail 3": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Pony Tail3.png",
            "Baby": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Baby.png",
            "Black Beanie": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/BeanieBlack.png",
            "Orange Beanie": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/BeanieOrange.png",
            "Solana Beanie": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/BeanieSolana.png",
            "Daisy": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Daisy.png",
            "Horns": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/DevilHorns.png",
            "Halo": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Halo.png",
            "Black Hat": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Hat.png",
            "Headband": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Headband.png",
            "Mohawk": "https://staging.opos.quest/attributes/Heads/Hair/Hair:Hat/Mohawk.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
        "Torso": {
            "TipLink Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/White.png",
            "Black Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/Black.png",
            "Blue Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/Blue.png",
            "Gold Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/Gold.png",
            "Green Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/Green.png",
            "Grey Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/Grey.png",
            "Red Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/Red.png",
            "Solana Blue Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/SolBlue.png",
            "Solana Green Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/SolGreen.png",
            "Solana Purple Shirt": "https://staging.opos.quest/attributes/Torso/Shirt/SolPurple.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
        "Logo": {
            "TipLink": "https://staging.opos.quest/attributes/Torso/Logos/TipLink.png",
            "Helius": "https://staging.opos.quest/attributes/Torso/Logos/Helius.png?1",
            "Helium": "https://staging.opos.quest/attributes/Torso/Logos/Helium.png",
            "Metaplex": "https://staging.opos.quest/attributes/Torso/Logos/Metaplex.png",
            "Solana": "https://staging.opos.quest/attributes/Torso/Logos/Solana.png",
            "Solarplex": "https://staging.opos.quest/attributes/Torso/Logos/Solarplex.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
        "Legs": {
            "TipLink Pants": "https://staging.opos.quest/attributes/Legs/Pants/Blue.png",
            "Brown Pants": "https://staging.opos.quest/attributes/Legs/Pants/Brown.png",
            "Dark Grey Pants": "https://staging.opos.quest/attributes/Legs/Pants/DarkGrey.png",
            "Light Grey Pants": "https://staging.opos.quest/attributes/Legs/Pants/LightGrey.png",
            "Gold Pants": "https://staging.opos.quest/attributes/Legs/Pants/Gold.png",
            "Green Pants": "https://staging.opos.quest/attributes/Legs/Pants/Green.png",
            "Khaki Pants": "https://staging.opos.quest/attributes/Legs/Pants/Khaki.png",
            "Magenta Pants": "https://staging.opos.quest/attributes/Legs/Pants/Magenta.png",
            "Red Pants": "https://staging.opos.quest/attributes/Legs/Pants/Red.png",
            "Solana Pants": "https://staging.opos.quest/attributes/Legs/Pants/Solana.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
        "Feet": {
            "TipLink Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/Grey.png",
            "Black Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/Black.png",
            "White Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/White.png",
            "Blue Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/Blue.png",
            "Gold Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/Gold.png",
            "Green Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/Green.png",
            "Red Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/Red.png",
            "Solana Blue Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/SolBlue.png",
            "Solana Green Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/SolGreen.png",
            "Solana Purple Shoes": "https://staging.opos.quest/attributes/Feet/Shoes/SolPurple.png",
            "None": "https://staging.opos.quest/attributes/None.png",
        },
    },
}